### ISSUE TITLE
Search: Jump to post sporadic/not working in iOS

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat.Cordova#101]
Rocket.Chat version: 0.27.0
iOS app version: 2.3.1

I'm not sure if this is a Rocket.Chat or Cordova specific issue, and I can only test on iOS.

When using search jumping to a specific post seems spotty. On my iPhone it doesn't seem to work at all. On my iPad it works for the first post tapped on, but not on subsequent ones.

**Comment by geekgonecrazy** [comment]
@rebeld this should work as of Server version 0.28.0 was fixed in https://github.com/RocketChat/Rocket.Chat/commit/b813ec8f30a9d38375d0f3da68c6321c1c63a709
