### ISSUE TITLE
What method can make rocket.Chat.Cordova and rocket.chat Compile together?

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/Rocket.Chat.Cordova#103]
I want to compile a apk point to my own deployment server code, I want to start my server address set up, and make rocket.chat program code compiled in the apk (I don't want users to download apk installed it and also need an update operation), the idea can be implemented?

**Comment by geekgonecrazy** [comment]
You'll need to add your server in to the server list so its joined by default.  We leave this up to you to implement as you wish.  This code backs our app in the app store which is always going to be multi server, so it doesn't need to connect to one single server.
