### ISSUE TITLE
Improve battery usage

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Cordova#112]

**Comment by TheReal1604** [comment]
If you can improve the battery usage, this would be really nice.

On iOS i have a battery usage around 10% with normal usage, on a nexus 5 android 6 device, the battery usage is around 40% to 60% thats way to much..

**Comment by geekgonecrazy** [comment]
@TheReal1604 Can you take a couple of screenshots of this?  Mainly will be useful to know what change in network conditions etc happened.

**Comment by TheReal1604** [comment]
Hello Aaron,

did you need an exact view? I can send you some battery consumption screenshots from  android settings this afternoon.. Is that fine?

Am 08.06.2016 um 00:11 schrieb Aaron Ogle <notifications@github.com<mailto:notifications@github.com>>:

@TheReal1604https://github.com/TheReal1604 Can you take a couple of screenshots of this? Mainly will be useful to know what change in network conditions etc happened.

##

**Comment by TheReal1604** [comment]
Hello Aaron,

when i look at my reverse proxy i see some crazy get requests from only this android device, the URL is deformed..

The requests look like this:

192.2.213.63- - [08/Jun/2016:10:37:42 +0200] "GET /_timesync HTTP/1.1" 200 695 "http://httpsyourdomainde.meteor.local/direct/test" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MOB30H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Crosswalk/15.44.384.13 Mobile Safari/537.36"

A normal request from other devices look like:

192.168.213.2 - - [08/Jun/2016:10:37:32 +0200] "POST /sockjs/682/24kh62u4/xhr_send HTTP/1.1" 204 421 "https://chat.yourdomain.de/direct/test2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat+/1.3.1 Chrome/47.0.2526.110 Electron/0.36.10 Safari/537.36"

This requests occurs then the device is locked, too. Can this be related?

Here is a screenshot:

![shared file](https://cloud.githubusercontent.com/assets/5877910/15888020/884fb304-2d65-11e6-87b6-dfcb3d24701b.jpg)

**Comment by geekgonecrazy** [comment]
@thereal1604 this is due to the caching. It is pretty weird request made it to your nginx.

Do you happen to have one of the network connectivity during that time period as well.

Mainly want to make sure usage isn't so high because of a lot of network changing

**Comment by TheReal1604** [comment]
Did you need more information / logs / screenshots? I think we really need to improve this.

@geekgonecrazy Did you have an idea what causes this malformed requests? Should i create an additional issue?

**Comment by geekgonecrazy** [comment]
@TheReal1604 if you tap on Rocket.Chat it should give you more information.  The information inside there is what's more useful. :smile:

**Comment by TheReal1604** [comment]
@geekgonecrazy ![photo-2016-06-12-08-43-21_3279](https://cloud.githubusercontent.com/assets/5877910/15989628/2617c860-307c-11e6-94af-40fd704d4aca.PNG)

**Comment by TheReal1604** [comment]
Some more screenshots...

![screenshot_20160615-153801](https://cloud.githubusercontent.com/assets/5877910/16081833/8d4179f6-330f-11e6-9b8f-58cb0f7f80a9.png)
![screenshot_20160615-153808](https://cloud.githubusercontent.com/assets/5877910/16081834/8d4270fe-330f-11e6-9f19-9be3c8310967.png)

**Comment by frdmn** [comment]
/cc @geekgonecrazy - Regarding the malformed requests: 

I just found this: https://github.com/RocketChat/Rocket.Chat.Cordova/blob/787bef577d3155c1eaa2a6b663dfd2e83a28f87d/www/coffee/servers.coffee#L437

Not really sure what it does exactly and why, but it seems like it's the place where said "weird" URL is put together.

Edit: fixed link

**Comment by geekgonecrazy** [comment]
@frdmn interesting.  I wasn't aware of malformed requests on mobile.  I know on electron we have some with jitsi.

@TheReal1604 Just out of curiousity do you have the app open frequently or leave it up when you let the screen timeout?  Because it does look to be using a lot of network traffic.  Way more then I normally see even on mine.

Also do you know if your server is using websockets to connect?  I can see a case if its having to use polling instead that it would consume a lot more battery.

**Comment by TheReal1604** [comment]
@geekgonecrazy Yes, the app is used exactly the way you described by my girlfriend, from her android nexus 5 are the screenshots. She is using this now in another way (lock the screen immediately after using the app.) Thats a little bit better than before.

Sry, i don´t know if its using web sockets, can you please explain how i can look what i am using? I use the docker container on my ubuntu server that you provide. (the rocket.chat team) The requests on my reverse proxy include "sockjs", did that mean i use web sockets?

In addition i have only a ubuntu server apache2 reverse proxy in front of this (dedicated machine).

**Comment by geekgonecrazy** [comment]
@TheReal1604 so let me get this straight...
- Locking screen with app still up -- Better performance
- Switching to home screen and then locking -- worse performance?

Can you check if apache2 reverse proxy is forwarding websockets?  I don't think it does with out special configuration.  To check open chrome or firefox to your chat.  Open the developer console (ctrl+shift+I) then goto the network panel and refresh.  Check the WS tab and you should see something like this:

![screenshot 2016-06-24 at 10 10 10 pm](https://cloud.githubusercontent.com/assets/51996/16354402/755179ea-3a58-11e6-9b93-145b2f75a6cc.png)

**Comment by TheReal1604** [comment]
Hey Aaron, 

yep, it's like you said.  I searched for Apache 2.4 and proxying web sockets, I don't have the mod_proxy_wstunnel enabled. So, that's the next step that should I go. I look for some documentation, setup this and then give you feedback if it's better now.

**Comment by geekgonecrazy** [comment]
@thereal1604 I suspect much better performance.  Though I know we have room for improvements.

Feel free to create a doc in our documentation for enabling this for apache2.  I'm sure it'd be useful for many others like your self

**Comment by TheReal1604** [comment]
The funny thing is, it is already in your docs. 

https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy-with-nginx

At the end... ;-)

**Comment by geekgonecrazy** [comment]
👍 let me know how the battery usage changes

**Comment by TheReal1604** [comment]
@geekgonecrazy here are some news on this issue:

i have implemented the websocket functionality on the reverse proxy with this conf:

```
#Proxy
SSLProxyEngine On
ProxyPreserveHost On
ProxyPassMatch ^/sockjs/(.*)/websocket ws://192.168.2.240:3000/sockjs/$1/websocket
ProxyPass / http://192.168.2.240:3000/
ProxyPassReverse / http://192.168.2.240:3000/
```

But there is not much improvement on the battery usage side:

![screenshot_27062016-1](https://cloud.githubusercontent.com/assets/5877910/16385220/407a4a7c-3c8c-11e6-96fb-5e67e327c6cb.jpg)
![screenshot_27062016-2](https://cloud.githubusercontent.com/assets/5877910/16385221/40903ff8-3c8c-11e6-90be-a1a6f365e936.jpg)

Here is a screenshot from the developer console in chrome:

![image](https://cloud.githubusercontent.com/assets/5877910/16385465/2edc6808-3c8d-11e6-82e6-0c57d20a8810.png)

I checked the configuration and your mentioned "websocket" entry in the developer console exists. (If i look at transmitted packets under network).

Did you have some other things to check why this happen?

EDIT: Added screenshots and edit some formatting

**Comment by TheReal1604** [comment]
I think we really need a solution for this. This is an absolute showstopper for our android users. Some experience from other Admins would be really nice! Because it could be an issue with my environment.. But don't know what to change. 

 ¯_(ツ)_/¯

**Comment by TheReal1604** [comment]
Got a temporary workaround for this with @Sing-Li help. Disabled background data usage for the rocket.chat app. Now it's working. The only disadvantage of this is, that the entire app is reloading when you open the app from background.

**Comment by Sing-Li** [comment]
@TheReal1604   This is VERY valuable information.

For one thing, it CONFIRMS that network usage IN BACKGROUND is the culprit.  It gives us something concrete to go on in attempt to alleviate the problem.

Can you please measure and post the difference in power consumption with this kludge?   Thanks again.

**Comment by TheReal1604** [comment]
![shared_file](https://cloud.githubusercontent.com/assets/5877910/16865444/27eb4ede-4a65-11e6-9ab8-0d79f990eac3.png)

Thats the first screenshot.. will add the detail information later. My user said that the network interface is now only up around 9-10 minutes! Not 4 hours like in the other screenshots.

**Comment by geekgonecrazy** [comment]
@TheReal1604 btw 2% wouldn't really be considered high battery consumption.

**Comment by graywolf336** [comment]
For those following this thread, I have submitted a pull request which needs testing: https://github.com/RocketChat/Rocket.Chat/pull/3808

Basically we would be listening for when the application goes into the background so we can disconnect from the server and then when the application comes back into active we reconnect. I was only able to test it a tiny bit locally, so I'm hoping we can test using the deployment which was requested in that pull request to test it further.

**Comment by TheReal1604** [comment]
@graywolf336 Thats awesome, thanks that you create a solution for  this annoying issue.

Here is the other screenshot with details:
![shared 20file](https://cloud.githubusercontent.com/assets/5877910/16951560/d03660de-4dc5-11e6-8c6c-43aaa36384a3.png)
