### ISSUE TITLE
Steps to upgrade the server application.

### ISSUE THREAD

**Issue by neohitokiri** [RocketChat/Rocket.Chat.Cordova#117]
What are the steps that must be performed to update the application?, recompile and overwriting files?. I have installed the version "0.28.0" and I want to upload it to the "0.34.0".

I want to minimize the possibility of incidents occurring. How I can make a backup of the database and files related to the current deployment ?.

I am using **Windows Server 2012 R2**, the steps I followed to the current compilation are detailed in the url "https://rocket.chat/docs/installation/manual-installation/windows-server/" but can not connect the server via the mobile application. I use **NGINX** as a reverse proxy application and there have configured a valid SSL certificate as"https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy-with-nginx".

**Comment by geekgonecrazy** [comment]
@neohitokiri this issue tracker is for the mobile app.  You're more likely to get a response on how to update on the server repo: https://github.com/rocketchat/rocket.chat/issues in our [#support](https://demo.rocket.chat/channel/support) channel. 

Mobile support does not work currently in the windows build: https://github.com/RocketChat/Rocket.Chat/issues/3631
