### ISSUE TITLE
Cannot Compile Rocket Chat Cordova 

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat.Cordova#118]
Here is my cordova version information:
Cordova Version 6.2
Installed platforms:
  android 5.1.1
  ios 3.9.2
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0

<img width="788" alt="sdk" src="https://cloud.githubusercontent.com/assets/138841/16419556/71c72b3c-3d4e-11e6-9d68-b5a84a59bde6.png">

When I run "cordova build android" I get the following:
:processArmv7DebugManifest
:processArmv7DebugResources
:generateArmv7DebugSources
:compileArmv7DebugJava
/Users/johnhand/Documents/Sandbox/clarapy-3/Clarapy.Chat.Cordova/platforms/android/src/nl/xservices/plugins/GooglePlus.java:11: error: package com.google.android.gms.auth does not exist
import com.google.android.gms.auth.GoogleAuthException;

How can I fix this?

**Comment by gotev** [comment]
I had the same issue. Probabily Google has changed something in their latest GooglePlus and CloudMessaging artifacts, which breaks compatibility. I'm going to explain how I've fixed it.

### Manual substitution

Edit `plugins/cordova-plugin-googleplus/plugin.xml`

and change

``` xml
<framework src="com.google.android.gms:play-services-plus:+" />
<framework src="com.google.android.gms:play-services-identity:+" />
```

to

``` xml
<framework src="com.google.android.gms:play-services-plus:9.0.2" />
<framework src="com.google.android.gms:play-services-identity:9.0.2" />
```

Edit `plugins/phonegap-plugin-push/plugin.xml`

and change

``` xml
<framework src="com.google.android.gms:play-services-gcm:+" />
```

to

``` xml
<framework src="com.google.android.gms:play-services-gcm:9.0.2" />
```

### Automated substitution

If you are on OS X or Linux, you could simply perform the needed substitutions by executing:

``` shell
sed -i -e 's/com.google.android.gms:play-services-plus:+/com.google.android.gms:play-services-plus:9.0.2/g' plugins/cordova-plugin-googleplus/plugin.xml
sed -i -e 's/com.google.android.gms:play-services-identity:+/com.google.android.gms:play-services-identity:9.0.2/g' plugins/cordova-plugin-googleplus/plugin.xml
sed -i -e 's/com.google.android.gms:play-services-gcm:+/com.google.android.gms:play-services-gcm:9.0.2/g' plugins/phonegap-plugin-push/plugin.xml
```

### Apply the changes and re-build

``` shell
cordova platform remove android
cordova platform add android
cordova build android
```

And you should be able to build

**Comment by Syirrus** [comment]
The solution that @gotev offered works like a charm. Thank you so much for taking the time to post this. Any of us who were trying to compile for Android were dead in the water

**Comment by rodrigok** [comment]
Awesome, can we close this issue?

**Comment by gotev** [comment]
[The fix](https://github.com/phonegap/phonegap-plugin-push/pull/1044) for `phonegap-plugin-push` has been merged. Waiting for `cordova-plugin-googleplus`. Theoretically, if the pull request gets merged, the solution I've proposed will no longer be necessary to build. However, in my opinion, this issue can be closed.
