### ISSUE TITLE
Beta Release

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat.Cordova#12]
#### Beta 1
- [x] Save current selected server and load selected server on app load
- [x] Use ionic keyboard plugin to resize the iframe on keyboard show/hide
- [x] Allow delete servers
- [x] Loading screen when downloading server files
- [x] Loading screen when opening a server
- [x] Splash screens
- [x] Icons
- [x] Some indication how to open the servers list
#### Beta 2
- [x] Delete server folder when delete server
- [x] Facebook Login
- [x] Push Notifications
#### Beta 3
- [x] Retry download files
- [x] Add a default cache copy to prevent download of some files
- [x] Update server
#### Beta 4
- [x] UserPresence
- [x] Open links in a browser window
- [x] Keep multiple servers logged
- [x] Timeout when trying to connect to a wrong url or ip
- [x] Load correct server when opening via push notification

**Comment by rockneverdies55** [comment]
Great job @rodrigok. You're awesome. :-)

**Comment by graywolf336** [comment]
Just tried to run this on my phone and I wasn't able to.

Here I tried with no server: https://drive.google.com/file/d/0Bzr2T-rWGn_5amxtY2NVcWRLZ2M/view?usp=sharing
Here I tried with a custom server instance: https://drive.google.com/file/d/0Bzr2T-rWGn_5QVhCdThFYVNtRzA/view?usp=sharing

Is there anything I can help you with?

**Comment by graywolf336** [comment]
Looked into it and upon adding a server I get the following error:

`servers.js:179 Uncaught TypeError: Cannot read property 'manifest' of undefined`
![2015-11-13_11-16-50](https://cloud.githubusercontent.com/assets/850391/11152436/0fbc8018-89f8-11e5-83a8-f0c5c6a6da7b.png)

**Comment by graywolf336** [comment]
Just now tried it again after reinstalling the application, works for demo but does not work for my custom server. Does the server need to be updated? @rodrigok

**Comment by graywolf336** [comment]
22708d82078f11d4003445d101a48d843ea8bac7 added some error handling which should help with anyone who is trying to get this going on their device as well. The error messages are hard coded at the moment, that's something we will need to do.

**Comment by rodrigok** [comment]
@graywolf336, servers must have the ios or android platform added.

Without mobile platform activated, meteor don't generate files for mobile, like the manifest.json and the index.html pointing to meteor.local.

**Comment by geekgonecrazy** [comment]
can we not replicate this?  Seems like something we wouldn't want to force them to do. Having to manually run meteor add to get access to the mobile apps seems like it shouldn't be needed from a deployment standpoint.

**Comment by rodrigok** [comment]
@geekgonecrazy we should add the ios platform in our builds.

**Comment by geekgonecrazy** [comment]
@rodrigok so we just have to add at least one platform?  I guess as long as its not installing the sdk stuff it won't add much bulk

**Comment by rodrigok** [comment]
@geekgonecrazy exactly, we just need to add the platform to tell to Meteor to generate all files that cordova will consume, this will not generate mobile apps or install sdk.
