### ISSUE TITLE
build error after upgrade sdk android

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat.Cordova#125]
today after upgrade the android sdk and a fresh Rocket.chat.cordova I have this error doing "cordova run android"

BUILD FAILED

Total time: 7.681 secs
Error: Error code 1 for command: /home/max/Rocket.Chat.Cordova/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/max/Rocket.Chat.Cordova/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

Here my SDK config
![x bug crc1](https://cloud.githubusercontent.com/assets/5683921/17781132/5ea2cf14-656e-11e6-96ba-3398a083cb35.png)
![x bug c r c 2](https://cloud.githubusercontent.com/assets/5683921/17781131/5ea2799c-656e-11e6-82b2-42887ad10160.png)
##

**Comment by Micjoyce** [comment]
@maxlinux2000  did you fixed this problem?

**Comment by maxlinux2000** [comment]
no, but I will close this bug because it's old and I opened onother one
