### ISSUE TITLE
After update the app is stuck at loading screen

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Cordova#126]
Hey Guys, 

after the update from the AppStore and google play store the app is stuck in the Loading screen. "Loading chat.domain.com". 

After a reinstall of the app all is working fine. 

I use the 0.37.0 on the server side.. Today I try the update to 0.37.1 and ask my users if this happens also on this.. 

Any suggestions? 

Greetings TheReal

**Comment by rodrigok** [comment]
@TheReal1604 can you test with latest version of mobile apps (2.4.0)?

**Comment by TheReal1604** [comment]
@rodrigok After the new update all is fine :+1:
