### ISSUE TITLE
Only locate user if he uses the geolocation post button

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Cordova#127]
Hey Guys,

after the update that was yesterday / today release I found that the GPS seems active all the time when the users use the RC app. This is represented by the gps icon in the right corner. You see this in the screenshot.

In my opinion this could lead to battery issues then heavy using this app. A possible solution could be to only locate the user if he press the button and then show the popup of the current location.

![photo-2016-08-23-12-19-49_3510](https://cloud.githubusercontent.com/assets/5877910/17888662/4b1a3c22-692c-11e6-83e0-39935675d282.PNG)

Any suggestions?

Greetings 
TheReal
##

**Comment by rodrigok** [comment]
Hi @TheReal1604, we keep tracking geo to have a very quick dialog to send geo when you click on button.

Maybe we should add an condition to get geo on click for mobile and keep tracking on desktop.

The code should check the position 1 time in each 10 seconds as you can see [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-message/message/messageBox.coffee?ts=2#L262) maybe the plugin for cordova does not support this feature and keep tracking the geo

**Comment by TheReal1604** [comment]
@rodrigok Thanks for the explanation. But it's not a good idea to locate the user before he uses this function.. Can establish distrust to the server admin or to the developers. ala "What the heck? Why keeps this app locating me because I don't use this feature." Okay, every user can deactivate the right to locate, but then he loses the ability to use this nice feature at all. IMHO.
