### ISSUE TITLE
After update, Geolocation post button is missing on android

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Cordova#128]
Hey Guys, 

for iOS devices the update was very straightforward all is working like a charm. After the update on android devices I see that the geolocation button is missing. The permission to locate the user from RC is enabled. 

![](http://i.imgur.com/Qcg28GU.jpg)

There is only the mic record button.

Greetings
TheReal

**Comment by geekgonecrazy** [comment]
When you started the application did you hit allow or deny when it asked for your location?

**Comment by TheReal1604** [comment]
The User deactivated the Geolocation lookup globally in the android system. After enabling this, all is working like a charm. Thanks for that!

**Comment by TheReal1604** [comment]
@geekgonecrazy We hit allow ;-) but.. See above. You're amazing fast. :D

**Comment by geekgonecrazy** [comment]
Good deal!  :smile:
