### ISSUE TITLE
Not connect with local development server.

### ISSUE THREAD

**Issue by bharatpatel2005** [RocketChat/Rocket.Chat.Cordova#129]
my local development Rocket.Chat server version is 0.37.1 (latest) and my cordova app also latest from github.

but in mobile app not connect to server, like #72 , #80 ,

and @rodrigok, also try and test https://github.com/RocketChat/Rocket.Chat.Cordova#i-cant-connect-to-my-server-instance, but still not connect.
##

**Comment by loredanacirstea** [comment]
If you by any chance are using a domain name set in your computer's `etc/hosts` file, take a look at: http://borkweb.com/story/setting-etchosts-on-an-android-emulator-using-a-mac

**Comment by geekgonecrazy** [comment]
Also if running in emulator, could be a network issue.  Going to close this since not really a bug, but more of a support thing.
