### ISSUE TITLE
Url configured in your server is not the same

### ISSUE THREAD

**Issue by Mte90** [RocketChat/Rocket.Chat.Cordova#136]
I get that alert:

```
The URL configured in your server (the server) is not the same that you are using there
```

When i click ok in that alert i get this view without any chance to to something
![screenshot_20160916-122859](https://cloud.githubusercontent.com/assets/403283/18583167/6e2e3ce8-7bf8-11e6-8286-fe783e6dd768.png)
Also the url of the alert is right so I have no idea how to fix, I was thinking to reset the data of the app and configure again.

**Comment by Mte90** [comment]
Ok removing the data of the app and configure again now is working without problems.

**Comment by geekgonecrazy** [comment]
@Mte90 alternatively next time.  Two finger swipe, hit delete by the server, and then add it again.

**Comment by Mte90** [comment]
well very easy to understand in the app XD maybe add instructions for it in that view simplify so much.

**Comment by geekgonecrazy** [comment]
@Mte90 we have it on the initial server add screen.  We haven't been able to find a cleaner way with out making the UI look bad, or reduce screen space :(  Maybe we could add a pop up when the app first starts explaining how to manage connected servers.

**Comment by Mte90** [comment]
well i mean when i get that error and in that view where there is this empty label add the instruction that you written before will be the easiest solution

**Comment by geekgonecrazy** [comment]
@Mte90 downside, is that alert is perfectly legit, and often things work just fine after that alert.  But I get your point.  Will investigate how we can add that.
