### ISSUE TITLE
App displaying UI weird since iOS10

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Cordova#137]
Hey Guys, 

since iOS 10 I get weird displaying issues in my rocket.chat app. It is caused mostly by reloading or reopening the app. It looks like in the screenshot attached. On the server side I use 0.40.1. Anyone has this issue also? 

![](http://i.imgur.com/CwMvLRD.jpg)

**Comment by TheReal1604** [comment]
After closing and reopening the app all is fine.. Just for information.

**Comment by TheReal1604** [comment]
@geekgonecrazy @engelgabriel @marceloschmidt No one has an idea? :(

(with the comment above i mean, after restarting the app all is fine for some time)

**Comment by rodrigok** [comment]
@TheReal1604 Strange, I never saw that. Is this still happening?

Is this happening on our demo server too?

**Comment by TheReal1604** [comment]
@rodrigok Couldn't test this on demo yet. I could replicate the issue if I use "Edge" or slow and unreliable networks.. Seems that there's an issue in caching or something like that. Some minutes ago I roamed from normal wifi to edge.. and the issue happens.

**Comment by TheReal1604** [comment]
It seems that there is a caching issue. If I upload a image when I have this issue, the message "Token invalid" appears and the image is not uploaded but a message is generated. @rodrigok We really need a fix for this. Or have you any idea what could wrong with my setups? I reinstalled already the rocket chat app on my phone and tested only with one server.

**Comment by TheReal1604** [comment]
Added Screenshot.... anyone have an idea? ![](http://i.imgur.com/NDSLnBU.jpg) What is causing this?

**Comment by geekgonecrazy** [comment]
this could be related to: https://github.com/RocketChat/Rocket.Chat/pull/4981

**Comment by TheReal1604** [comment]
Closing - resolved with actual versions of Rocket.Chat.
