### ISSUE TITLE
Beta: URL Window overlaps User/PW Window

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat.Cordova#14]
Samsung Galaxy S6 Edge, Android 5.1.1

Clean install. At the first lauch I misspelled the URL of my server. After I corrected the URL I was forwarded to the User/PW screen. But when I enter text into the user / PW field and the keyboard pops up it "pushes" the URL Dialog over the User / PW screen. So I can´t see what I am typing.... (but it still works, so I can logIn after blind input of User / PW).

**Comment by graywolf336** [comment]
Can you attach a screenshot? As this isn't the first time I've heard of this but I haven't experienced it myself.

**Comment by miscs** [comment]
this happens with my own server as well as with rocket demo server

focus is still on the underlying user / pw fields so its possible to log in....
![login](https://cloud.githubusercontent.com/assets/878463/11276278/c75dc11c-8ee1-11e5-88a3-cea5d3cd6795.png)

**Comment by rodrigok** [comment]
This issue was solved. Please update your app and try again.

**Comment by miscs** [comment]
works. thanks!
