### ISSUE TITLE
Clicking on a link inside the application should open it in an external browser

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat.Cordova#142]
Now it opens the link inside the application which isn't expected behaviour, and it is incredibly annoying and slow as well.
It should either open links in a chrome custom tab (https://developer.chrome.com/multidevice/android/customtabs) or in an external browser as a quick fix.

**Comment by rockneverdies55** [comment]
:100:  
I hate when I forgot about this and accidentally click on a link on the mobile...

**Comment by brnbs** [comment]
Accidentally opened an issue on other project. Please add an option for selecting an external app which is used for opening the clicked URL instead of displaying inside the app.

**Comment by bertptrs** [comment]
Any progress on this? The in-app browser is really slow and difficult (impossible? It tends to crash the app for me) to close.

**Comment by lunitic** [comment]
Would love if this got solved.. This is the biggest complain on the app we receives.

Is the solution in the app or is it in the server side?

**Comment by zookozcash** [comment]
Me too. This is the the worst problem I have with the mobile app right now.

**Comment by flaviogrossi** [comment]
these two changes seems to fix the issue for me: [one](https://github.com/VoiSmart/Rocket.Chat/commit/3896ff33bf6e2a457b735af7e55fb0dd67e7bf13) and [two](https://github.com/VoiSmart/Rocket.Chat/commit/0bdee2689871a2638ccacd7268f54c5d768b0220).

**Comment by geekgonecrazy** [comment]
@flaviogrossi would you be willing to open a PR with these changes?

**Comment by flaviogrossi** [comment]
@geekgonecrazy PR sent, please let me know if you find any issue with the code
