### ISSUE TITLE
Change the UI like or similar to Rocket.chat.android

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat.Cordova#165]
I just tried the new Rocket.chat.Android and its interface is much better than we have in Cordova.

I think the two interfaces would have to be the same or almost the same.

![screenshot_20161218-165608](https://cloud.githubusercontent.com/assets/5683921/21294690/0c7aa72c-c543-11e6-9bd5-e7e0b703aee6.png)

![screenshot_20161218-165912](https://cloud.githubusercontent.com/assets/5683921/21294700/7ea24f76-c543-11e6-9e36-a7cb1257ff71.png)

**Comment by geekgonecrazy** [comment]
The UI of this is driven by the Web app in the main server repo. We don't have a special UI just for this mobile app

**Comment by engelgabriel** [comment]
We are already working to make them more similar, taking the best of each one, but as @geekgonecrazy said, some components will only be available for native apps.
