### ISSUE TITLE
Upload the app also on F-Droid

### ISSUE THREAD

**Issue by Mte90** [RocketChat/Rocket.Chat.Cordova#168]
We are using RocketChat in an open source community and we have people that don't use Google Play but only F-Droid on Android systems.
So for us is important to have the app also on F-Droid (https://f-droid.org) that is an alternative market of only open source apps for android like this one.
So in few words it is possible to upload the android app also on f-droid?

**Comment by engelgabriel** [comment]
Can we do that @rodrigok @laggedHero ?

**Comment by geekgonecrazy** [comment]
This is a dupe.  A lot more conversation regarding that here: #104

**Comment by geekgonecrazy** [comment]
Closing in favor of: #104 lets keep this consolidated
