### ISSUE TITLE
Blue screen when server unavailable

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat.Cordova#19]
If the rocket server is unavailable the app shows just a blue screen.
You can slide up with two fingers, but if i don´t remember this im stuck. Would it be possible to show an error message in that case?

**Comment by graywolf336** [comment]
What do you mean by unavailable?

**Comment by miscs** [comment]
different possibilities
- you can access rocket server only in your company intranet -> try it outside your intranet, rocket server not reachable -> blue screen 
- rocket server is offline due to maintenance
- ...

I think in all these cases an error message would be nice instead of a blue screen :)

**Comment by graywolf336** [comment]
Is this from when you're adding a server or trying to connect to an
existing one from your list? Or starting up the application and it tries to
connect to your previous active server is when it happens?

**Comment by miscs** [comment]
the last one. I was connected with the server and starting the app again. in that case the app shows only a blue screen if it can´t connect. you still can swipe up with two fingers but an error message and hint to swipe with two fingers would be useful (not a high priority though)

**Comment by geekgonecrazy** [comment]
i've not seen this.  Can you check again and make sure this still occurs?  Also make sure the server supports the mobile app.

**Comment by rodrigok** [comment]
Should be fixed, please reopen this issue if not.
