### ISSUE TITLE
Issue with Google Play Store incompatible

### ISSUE THREAD

**Issue by teamsoo** [RocketChat/Rocket.Chat.Cordova#190]
I'm seeing this on my Samsung S8+ and Samsung Note 5

"CAT CDMA SPRD SMART MAX 4.0"

![](https://image.ibb.co/nMpC2k/Screen_Shot_2560_06_29_at_11_12_05_PM.png)

I'm not sure where to fix this incompatible. Any idea where I should look?

Running ***cordova run android --device*** works fine. but the app can't be installed from Play Store.

**Comment by geekgonecrazy** [comment]
@teamsoo what version of Android is installed?

**Comment by teamsoo** [comment]
@geekgonecrazy Maybe it's how I compile and release the apk. Thanks to your release.sh script. Now it's working. Thanks man.
