### ISSUE TITLE
Pulling in main project as dependancy

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat.Cordova#2]
to continue the discussion from RocketChat/Rocket.Chat#587 ...

**Comment by Sing-Li** [comment]
@rockneverdies55  - thanks for moving the thread  :smile:

My preference is not to add any more complexity to our build toolchain.

The Meteor build toolchain is already incredibly complex (when things go wrong, or toolchain dependencies break, hell breaks lose in the Meteor forums); and in this particular project, there is also the addition of the incredibly complex Cordova build toolchain(S - more than one!).  A casual perusal of the Cordova/Phonegap forums will convince anyone that it is almost perma-hell with so many dependencies and config variations.  I wouldn't rule out that bower is already in the chains, probably multiple times.

Complex unstable toolchain is probably the number one hurdle for 'on boarding' new members to open source JavaScript web projects.

The bet here is on those who need to run the toolchain tens, or even hundreds of times a day, to keep the toolchain efficient and in reasonable working order.
