### ISSUE TITLE
So can this run on Windows Phone as well? Or perhaps even a universal app?

### ISSUE THREAD

**Issue by Martinspire** [RocketChat/Rocket.Chat.Cordova#20]
So i've been looking into what Rocket Chat can do and having a Cordova solution might be nice. But i'm not sure if this will work properly on a Windows Phone or that we perhaps need to adjust/fix it. Has anybody tried? Are there examples?
I don't see it mentioned in the readme, nor do i see some WP-things in it. Would love to give it a go, but like some info before i waste my time

**Comment by graywolf336** [comment]
I don't believe any work has been done with Windows phone. But if anyone
has experience with it and wants to work on it, we would be happy to have
their help.

**Comment by Martinspire** [comment]
Nobody tried it? Hmm. I could give it a go to see if it works or not

**Comment by geekgonecrazy** [comment]
I have a windows phone in a drawer.  But its not my daily driver.  That would be cool to see it there as well.

**Comment by dmartinpro** [comment]
Any news about this?

**Comment by HammyHavoc** [comment]
@Martinspire Did you ever get started on this? Would be interested in collaborating.

**Comment by Morgy93** [comment]
I got some experience with Apache Cordova and Windows, but only in connection with Visual Studio. (Because it's super easy :D)
I'm trying to get this working somehow with Visual Studio, but currently I'm stuck at the following error: `1>MSBUILD : cordova-build error : Please install ImageMagick.`
So let me figure out how to get ImageMagick into Visual Studio and I'll report back to you.
Probably it's totally wrong what I'm doing here anyway.. we'll see. :D

**Comment by graywolf336** [comment]
Image magic is something you install at the Windows level, hopefully then
it'll get past that stage.

**Comment by Morgy93** [comment]
Yes, I can confirm it. It does run on Windows!
![rocketchat_cordova_win](https://cloud.githubusercontent.com/assets/7961978/14360551/3ceb306c-fcf7-11e5-9e8e-424e1aff0253.png)

There is actually just one little code change I had to do:
config.xml: `<preference name="Orientation" value="all" />`
The value "all" is not allowed, I changed it to "default". (For portrait and landscape)

**Comment by Morgy93** [comment]
Windows-64x - Local Machine:
![rocketchat_cordova_win64](https://cloud.githubusercontent.com/assets/7961978/14360745/119903f2-fcf8-11e5-8204-1f7553f1b8ac.png)

**Comment by Morgy93** [comment]
By the way .. I am also able to run this with Android and iOS within Visual Studio. =)

**Comment by geekgonecrazy** [comment]
@Morgy93 this is excellent!  So other then that it works well?  We need to look at getting it listed in the windows store then 😄

**Comment by graywolf336** [comment]
@Morgy93 Mind hitting me up on the demo server? I'm curious to see if I can get my Visual Studio to load this up!  👍

**Comment by Morgy93** [comment]
Actually all I did was loading up a blank Apache Cordova project within Visual Studio and copied over all the files from this repo.
After some minor work I was able to debug the project.
I did no further work than this. =/

**Comment by Martinspire** [comment]
@Morgy93 no problem, just put it in a github repo (fork, branch or create new) so people can take a look and try it out. I would imagine it doesn't take a lot of work or that it probably doesn't have any major issues but its the little ones that are easy to miss but quickly found if people can try it out easily.

Perhaps even create an executable for people to load or sideload would be fine as well.
