### ISSUE TITLE
Can't connect to Server if URL contains Port

### ISSUE THREAD

**Issue by j0hannesr0th** [RocketChat/Rocket.Chat.Cordova#217]
Hello,
I've discovered a bug.

I'm running Rocket.Chat on rocketchat.mydomain.tld - nginx ssl proxy listens on Port 33333.
So the Webinterface works fine when I use the URL https://rocketchat.mydomain.tld:33333 - this app unfortunately doesn't work. It just displays an red alert saying "Error while connection to the server: abort. abort".

**Comment by Izzur** [comment]
As a workaround, you can try using reverse proxy on your nginx configuration so it redirect traffic on port 80/443 to port 33333
