### ISSUE TITLE
Can't locate "www/shared/js/android_sender_id.js" if Rocket.Chat was installed with snap

### ISSUE THREAD

**Issue by j0hannesr0th** [RocketChat/Rocket.Chat.Cordova#218]
Hello,
I've installed Rocket.Chat with Snap. I've configured pushnotifications for Android like it is described here: https://rocket.chat/docs/administrator-guides/notifications/push-notifications/

I use the Cordova-App. So according to the documentation i should put my android ID to this file android_sender_id.js. But I can't find it.

It causes that my desktop notifications work fine, but mobile notifications don't work even if they are enabled. The test push notification works on my android phone but all other notifications don't work on my android phone.

I've tried to locate this file with "find / -name android_sender_id.js" on my server but I didn't find it.

So what can I do to fix this? Do I have to build the Cordova App on my own?

**Comment by teamsoo** [comment]
@hmr-it-jr Hi, you'll have to create the file by yourself. Just put the file in the correct path.
