### ISSUE TITLE
who knowns why cordova deprecated？

### ISSUE THREAD

**Issue by Mingyiz** [RocketChat/Rocket.Chat.Cordova#231]
i am js programer，with cordova it makes possible do some customer dev only code once. but now i have to learn android ios native dev langrange 😓

**Comment by sampaiodiego** [comment]
the cordova app performance was always poor. we also had to do some changes to Meteor (the framework we use on main project) code to support the features we need and keeping this changes updated was becoming harder and harder.

as a JS programmer you still have the opportunity to work with https://github.com/RocketChat/Rocket.Chat.ReactNative which is far better alternative to Cordova.
