### ISSUE TITLE
Need for custom branded iOS build

### ISSUE THREAD

**Issue by GaWr26** [RocketChat/Rocket.Chat.Cordova#26]
This might be a stupid question but I am not a iOS Developer. 

How would I approach compiling the iOS App for our company. I have a certificate and made a distribution provisioning profile but of course the App ID etc don't match.

**Comment by tholu** [comment]
+1 for a short customization/distribution guide, since the current native iOS app does not support multiple servers as far as I can see.

**Comment by rodrigok** [comment]
@flashguy22 and @tholu we are in beta testing of the new app that supports multiple servers, do you still need this?

**Comment by tholu** [comment]
@rodrigok I still can see the appeal of releasing an already customized/branded app (e.g. for the own company) with a custom preset server. However I also understand if you don't want to support that officially.

**Comment by rodrigok** [comment]
@tholu we don't have problems with this, but now we are only in the beta releases, this is not ready for production yet and we are dedicating our time to finish the project ASAP.

If someone wants helps us creating this tutorial we can add into our README or our Wiki page.

:smile:

**Comment by tholu** [comment]
@rodrigok Getting the project out of beta has of course priority. What's the current stance on the native iOS app, will it be deprecated or will both the native iOS-App and the multiplatform-Cordova coexist and be further developed?

**Comment by rodrigok** [comment]
As the Cordova project can share almost all the code from our web app and is all JS, HTML and CSS is much more easy for us to develop and maintain with all features.

We don't have developers that knows Java or ObjectiveC/Swift to help or lead the native projects, so these projects are been leaded and developed by the community.

Of course we prefer the native apps, but for now the hybrid app is what we can create here as fast as possible.

When the native versions become better than the hybrid apps, probably we will replace.

**Comment by pdehaye** [comment]
Hi, I just tried the RocketChat beta iOS app, and it doesn't work with my own install of RocketChat via Sandstorm. If I try using the Sandstorm webkey, I get a "The address provided is not a Rocket.Chat server" error. 

Since @engelgabriel 's name is listed as maintainer of the RocketChat Sandstorm app, and since he sent me the beta invite, I guess he should be mentioned here  :P

**Comment by rodrigok** [comment]
@pdehaye good question, I will open a specific issue for this point.

**Comment by engelgabriel** [comment]
Probably relates to https://github.com/RocketChat/Rocket.Chat/issues/1352

**Comment by engelgabriel** [comment]
@pdehaye Can you check if the `X-Rocket-Chat-Version` is preset or have been removed from the grain response? Are you using the app from the App Market or from https://s3.amazonaws.com/rocketchatbuild/rocket.chat.latest.spk ?

**Comment by pdehaye** [comment]
I am using the app via the beta invite you sent me 3h40 ago, which I am running on my iPhone via Testflight. I don't know how to check the grain response.

**Comment by engelgabriel** [comment]
How did you install the grain?

**Comment by pdehaye** [comment]
I was trying the app from the App Market, but (finally) got your hint and installed the latest build. With that app I can't start a grain, I get this in the app's log:

```
** SANDSTORM SUPERVISOR: Starting up grain.
sandstorm/supervisor.c++:1144: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.
*** Uncaught exception ***
sandstorm/sandstorm-http-bridge.c++:1762: failed: execvp(argvp[0], argvp): No such file or directory; argvp[0] = /opt/app/.sandstorm/launcher.sh
stack: 0x5057b9 0x5057aa 0x472b91
```

This could happen because I am using a "productive" install of sandstorm and not a dev one?

**Comment by engelgabriel** [comment]
I've just opend an issue https://github.com/RocketChat/Rocket.Chat/issues/1496

**Comment by paulproteus** [comment]
BTW, I believe Sandstorm will eat the `X-Rocket-Chat-Version` header at the moment. There's work going on to let Sandstorm support headers of the form `X-Sandstorm-App-*` which could be used for this, but that's not quite ready yet.

**Comment by paulproteus** [comment]
Sort-of apologies that Sandstorm is a bit weird in that regard; but I at least wanted to make sure to mention that here.

**Comment by Sing-Li** [comment]
@paulproteus ....thanks for the explanation!

**Comment by pdehaye** [comment]
The original question did not mention sandstorm, although it could offer a solution. Also, there is a typo in the tag.

**Comment by tholu** [comment]
When is the release of the current version (supporting own servers) planned? Would be great to have this a soon as possible.

**Comment by engelgabriel** [comment]
It will be as soon as possible, probably this week.

**Comment by tholu** [comment]
@engelgabriel Great!

**Comment by tholu** [comment]
How to get iOS Beta access? Really looking forward to try the iOS App with our own deployment.

**Comment by rodrigok** [comment]
@tholu you can send your apple id (email) to support@rocket.chat and we will add you to our test flight.

The new app version was submitted to apple review yesterday, will be available in 5 or 6 days we believe.

**Comment by rodrigok** [comment]
Since our app is working for multiple servers I will close this issue.

**Comment by S0U1SB4N3** [comment]
where can I get a working copy of the latest Cordova ios app the GitHub files crash

**Comment by geekgonecrazy** [comment]
The latest copy of the `Rocket.Chat` app is here: https://github.com/RocketChat/Rocket.Chat.Cordova
The latest copy of the `Rocket.Chat+` app is here: https://github.com/RocketChat/Rocket.Chat.IOS
