### ISSUE TITLE
Splice in Crosswalk Webview to support older Android 4.x devices

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat.Cordova#3]
https://crosswalk-project.org/

Definitive source of info:

https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview

**Comment by geekgonecrazy** [comment]
:+1:

**Comment by Sing-Li** [comment]
Looks like MDG has beaten us to it ....

https://github.com/meteor/meteor/commit/5bd971a1727ec437e64b8454a5ca43ffad780d82

... so in 1.2 - it will be `meteor add crosswalk`
