### ISSUE TITLE
URL configured is not the same as configured

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Cordova#34]
This started happening right after the newest beta.

![screenshot_20151128-104622](https://cloud.githubusercontent.com/assets/51996/11452933/ad8a563c-95bd-11e5-97d5-b4b267306397.png)

**Comment by graywolf336** [comment]
Can confirm, on Android as well

**Comment by rodrigok** [comment]
@geekgonecrazy @graywolf336 are you accessing the demo server? And exactly which address you informed?

**Comment by graywolf336** [comment]
@rodrigok After clearing my data and removing the servers, it is no longer happening.

**Comment by rodrigok** [comment]
@graywolf336 good, please reopen this issue if you find the problem again

**Comment by geekgonecrazy** [comment]
Seemed with the latest this went away.  I had cleared data multiple times prior.  So this update must have fixed

**Comment by graywolf336** [comment]
Reopening as the issue has came back up. Seems that when you add a server the first time it works good, but then after quitting the application and the previous server loads the message displays. Android

**Comment by geekgonecrazy** [comment]
It has a pretty error message now.  :+1:  but still here on newest Android

**Comment by rodrigok** [comment]
@geekgonecrazy are you sure the url is correct? The same protocol?

**Comment by geekgonecrazy** [comment]
@rodrigok absolutely. I just put exactly: `https://demo.rocket.chat` It may not do it in your development version only in release?  Not sure.  It doesn't seem to do it right away.  Mainly on closing out completely then coming back and pulling from localstorage maybe?

**Comment by rodrigok** [comment]
@geekgonecrazy is this still occurs with the latest version of server and app?

**Comment by Morgul** [comment]
This was happening to me, but not longer is with the latest versions of server and app.

**Comment by geekgonecrazy** [comment]
I haven't seen this any more.  Going to go ahead and close until one of us experiences again.

**Comment by bennlich** [comment]
I just updated my server from 0.60.0 -> 0.62.2 and I'm seeing this error whenever I quit the rocket chat app and reopen it. Everything seems to work fine after I dismiss the error popup.
