### ISSUE TITLE
Two finger swipe not working

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Cordova#35]
Two finger swipe seems to not be working any more.  It seemed to stop working the last beta and also still this one

**Comment by sampaiodiego** [comment]
It's working on "connection screen", but not after connect to a server. in android btw

**Comment by geekgonecrazy** [comment]
@sampaiodiego I've had once or twice it not work on connection screen.  But mainly once connected

**Comment by graywolf336** [comment]
Seems to be fixed when on a server..but when you are on the server add view, you can't two finger swipe up.

**Comment by geekgonecrazy** [comment]
This seems to work.  Closing.  Will reopen if it shows back up
