### ISSUE TITLE
File Uploads Not Working [$10]

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Cordova#36]
Can't upload a file from the device, no errors displayed or anything.
##

**Comment by rodrigok** [comment]
@graywolf336 still happening? iOS or Android?

**Comment by graywolf336** [comment]
@rodrigok Yes, on Android.

**Comment by rodrigok** [comment]
JFYI Is working on iOS

**Comment by soenkef** [comment]
+1 File upload doesn't work in Android 4.4.4 and >5. The website file-upload runs.

**Comment by kreuzebek** [comment]
+1. File upload doesn't work ->  Android 4.0.3

**Comment by pschonder** [comment]
+1

**Comment by geekgonecrazy** [comment]
Just checked with 2.2.1 It does open a file picker, but doesn't seem to do the upload.  I don't think it opened the file picker before.

**Comment by soenkef** [comment]
File upload doesnt't work. Same with the last version. Filepicker opens and select item is possible but then ends. No dialog whether to upload or cancel, no file transfer.

**Comment by stoufa88** [comment]
+1 File upload doesn't work also on Android 4.4

**Comment by jcardila** [comment]
+1 Doesn't work on Android 5.1 and 4.4.4

**Comment by soenkef** [comment]
@rodrigok: Any idea?

**Comment by rodrigok** [comment]
@soenkef I spent some time trying to solve that problem with no success. Maybe someone can help me.

**Comment by pschonder** [comment]
@rodrigok, have you seen the PR?

**Comment by rodrigok** [comment]
@pschonder I'm sorry, I didn't see.

Great solution :smile:, I will try and merge your PR if works for me

**Comment by alokraj68** [comment]
having this issue on 0.70.4
