### ISSUE TITLE
Links not opening

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Cordova#37]
Nothing happens when clicking links

**Comment by graywolf336** [comment]
Can confirm, on Android

**Comment by rodrigok** [comment]
@geekgonecrazy @graywolf336 still happening?

**Comment by graywolf336** [comment]
@rodrigok Yes

**Comment by rodrigok** [comment]
JFYI Is working in iOS

**Comment by soenkef** [comment]
Confirm, that link not open on Android 4.4.4 and Android 5.0.

**Comment by Morgul** [comment]
Also confirming that links don't open on Android 6.0.

**Comment by kreuzebek** [comment]
Links and images not open In Edge Browser. Before works. It's the only way to use Rocket.Chat on windows phone

**Comment by rodrigok** [comment]
@kreuzebek please open a new issue on our server repo https://github.com/RocketChat/Rocket.Chat since this issue is not related with our Cordova apps.

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/c33a446759c4a33bb898581c5e64f4fecd0f9433

@soenkef, @Morgul, @graywolf336, @geekgonecrazy can you try?

**Comment by geekgonecrazy** [comment]
@rodrigok it prompted me about an update from the server, that didn't work.  

I then cleared the data and re-added the server, and it worked.  So resolved
