### ISSUE TITLE
"loading undefined" when connecting to a new server

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Cordova#41]
When you connect a server for the first time you got the message: "loading undefined", as shown below:

![image](https://cloud.githubusercontent.com/assets/8591547/11572211/3f9e24ea-99e7-11e5-8350-921266520f51.png)

**Comment by rockneverdies55** [comment]
Confirming the issue.

**Comment by graywolf336** [comment]
Confirming it as well.

**Comment by geekgonecrazy** [comment]
Yeah I noticed this as well.  You beat me to posting this.

**Comment by jashot7** [comment]
I confirm getting this exact problem on the iOS app. Before getting this problem, I was getting a 'hang' upon login to our custom server instance - but I can no longer duplicate that. Looking forward to a fix for this as our whole team wants to use the iOS app :)

**Comment by jashot7** [comment]
We updated our server and deleted and reinstalled the iOS apps. We still get the undefined message, but now the app takes us to the login screen appropriately. Everything is working for us. Awesome.

**Comment by rodrigok** [comment]
Sorry guys, this is a render issue, not a big problem, was solved on Android, will be solved for iOS on the next update.
