### ISSUE TITLE
App/Rocket.Chat language

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Cordova#42]
When using the android app, rocket.chat is always in English, even if the chosen language is a different one.

the app language (server list, loading messages, etc) is using the system language correctly.

![image](https://cloud.githubusercontent.com/assets/8591547/11572513/df21c534-99e8-11e5-80f6-1f0e62999d01.png)

**Comment by geekgonecrazy** [comment]
So this needs to some how trigger it to redownload right?

**Comment by sampaiodiego** [comment]
I really don't know what is the problem here =\

**Comment by soenkef** [comment]
+1 - language Not selectable

![screenshot_2015-12-11-16-37-48](https://cloud.githubusercontent.com/assets/16257281/11747840/af2ba4e2-a025-11e5-9044-7a1ad04690ca.png)

**Comment by rodrigok** [comment]
This is a Server Side issue and was solved by https://github.com/RocketChat/Rocket.Chat/commit/b2f18455cc6d761da4f088853ab793bddea3c508
