### ISSUE TITLE
Can't add second server

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Cordova#45]
- I connected to the https://demo.rocket.chat instance first. 
- I do the two finger swipe and add mine.  
- It acts like it takes it but then takes me back to the add screen with no error. (Also two finger swipe doesn't work here)
- I enter it again, and it clears it and connects to https://demo.rocket.chat instance again.

Adding mine first worked.  But then I had to click connect 3 times to get demo.rocket.chat connected second.

I've cleared and repeated this 3 times.  So hopefully easily reproducible :)

Android with the app version 2.1.0

**Comment by graywolf336** [comment]
Can confirm, just tried it myself.

**Comment by graywolf336** [comment]
Looking into this, it appears the `deviceready` event never fires after switching to the index page from the server list.

**Comment by marceloschmidt** [comment]
+1 here! Tried using two servers yesterday and it's a no-go.

I'm on Android App v 2.2.0

**Comment by geekgonecrazy** [comment]
This seems to be working.  Closing. Will reopen if it reappears
