### ISSUE TITLE
Can't switch servers from server list

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Cordova#46]
Both servers show up.  Clicking on one does nothing.  If I kill and then restart it switches to the server I selected.

So its saving it, just not changing.

Android App version 2.1.0

**Comment by graywolf336** [comment]
Can confirm as well.

**Comment by geekgonecrazy** [comment]
This seems to work now.  Going to close.  Will reopen if it shows back up

**Comment by mprentic-harris** [comment]
I don't see any way to switch servers on 2.3.1. :(
Ah, finally found the 2 finger swipe up to open the dialog. Very unintuitive.

**Comment by geekgonecrazy** [comment]
@mprentic-harris yeah we only display how to one place.  Suggestions on improving?
