### ISSUE TITLE
Cannot login with application

### ISSUE THREAD

**Issue by Tharnas** [RocketChat/Rocket.Chat.Cordova#48]
Hi,

I download the latest Rocket.Chat app from play store and provide my own server url (https://mydomain.com:8080). Afterwards I want to login but it stucks saying "PLEASE WAIT...." in the login button.

My environment:
Server is running with the latest docker image.
I connect with HTTPS and port 8080 through an reverse proxy.
For login ldap is used.

Things I already tried:
Use local IP address. (same behaviour)
Change port to 443. (same behaviour)
Login without reverse proxy and https. (same behaviour)
Login with webapplication from mobile works
Login to demo.rocket.chat works.

Many thanks in advanced

**Comment by sampaiodiego** [comment]
do you have the latest verions of server and mobile apps?
@geekgonecrazy had this problem but its now fixed.

**Comment by Tharnas** [comment]
Pulled again the latest version from docker and now its working.

Thanks you!

**Comment by sampaiodiego** [comment]
You're welcome! :smile:
