### ISSUE TITLE
Image file render fails

### ISSUE THREAD

**Issue by juliocbcotta** [RocketChat/Rocket.Chat.Cordova#52]
In the Android version, the render of uploaded files fails.
I am using the latest app version connected to the demo server.

**Comment by geekgonecrazy** [comment]
@BugsBunnyBR does the file actually upload, but it doesn't render?  Last I tested it, it didn't seem to even upload the file.

**Comment by juliocbcotta** [comment]
The file upload is not working. But files that were upload from the web client are not showing up in the Android Cordova app.
