### ISSUE TITLE
Can't login to custom instance with Android

### ISSUE THREAD

**Issue by mcescalante** [RocketChat/Rocket.Chat.Cordova#54]
I am running the latest server and application on my Nexus 6, and when I try to log into the instance, it just hangs at the login screen with no error indefinitely. The button reads "Please Wait..."

I do not see any output or access attempts either in the stdout for the application, or in my nginx access logs. I am running the application on a different port than 80, which I suspect may have something to do with the issue - maybe the login may not know about the port even though I input the URL with the port? Additionally, I am not running the app under https at the moment (testing).

I made sure I updated both client and server to the latest versions, and completely restarted both (also, reinstalled the Android app). Is this a known issue?

**Comment by geekgonecrazy** [comment]
How is the server being deployed? And is it at the current version?

You can check your version via: `http://{replace with your server hostname}/api/info`

**Comment by mcescalante** [comment]
Great question @geekgonecrazy  - right now I'm just testing it out by cloning the repository and spinning the application up with `meteor` (via `screen`). Could that be why there are issues?

**Comment by geekgonecrazy** [comment]
@mcescalante Yes I would recommend deploying using one of our guides.

https://github.com/RocketChat/Rocket.Chat/wiki#deployment

There are some things that have to be done to generate the files for mobile.  This is done automatically as part of our build process.

And honestly we don't recommend running with meteor for any sort of production environment.

**Comment by mcescalante** [comment]
Cheers @geekgonecrazy, makes sense - just wanted to note that I was only testing, and just didn't know what to expect running it with `meteor` (i.e. if mobile worked). I'm sure it's good in production and will report back here when I deploy properly for production that it's working as expected :smile:

**Comment by geekgonecrazy** [comment]
@mcescalante understandable :) Yeah its so inconsistent between machine to machine we really had no choice but distribute a compiled version.  Please let me know if you have any problems.  

Can find me at https://demo.rocket.chat @geekgonecrazy
