### ISSUE TITLE
mobile platforms enabled?

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat.Cordova#56]
In the Readme.md I can see:

 !!!Attention!!!
This application only connects with servers that were compiled with mobile platforms enabled

..but I don't understand it.

I have build with success the .apk but when I try to connect to my own Rocket.chat server or to the demo.server, the app can't download the files.
(my server rocket.chat works perfectly with the official android app.... gcm push notifications too)

So I suspect that the problem is the same that I can see in the Readme.

How to compile the server, with mobile enabled? 

I can't found any reference in the documentation, but in my server installation I can see the following structure.

root@myserver:~# tree Rocket.Chat/programs/web.cordova/
Rocket.Chat/programs/web.cordova/
├── 872308fb2236cf4d4e98500eeac12d33c21fa61a.js
├── app
│   ├── favicon.ico
│   ├── fonts
│   │   ├── fontello.eot
│   │   ├── fontello.html
│   │   ├── fontello.ttf
│   │   ├── fontello.woff
│   │   └── github
│   │       ├── octicons.eot
│   │       ├── octicons.svg
│   │       ├── octicons.ttf
│   │       └── octicons.woff
│   ├── images
│   │   └── logo
│   │       ├── 1024x1024-circle.png
│   │       ├── 1024x1024.png
│   │       ├── 512x512.jpg
│   │       ├── 512x512.png
│   │       ├── android-chrome-144x144.png
│   │       ├── android-chrome-192x192.png
│   │       ├── android-chrome-36x36.png
│   │       ├── android-chrome-48x48.png
│   │       ├── android-chrome-72x72.png
│   │       ├── android-chrome-96x96.png
│   │       ├── android-hdpi.png
│   │       ├── android-mdpi.png
│   │       ├── android-xhdpi.png
│   │       ├── android-xxhdpi.png
│   │       ├── android-xxxhdpi.png
│   │       ├── apple-touch-icon-1024x1024.png
│   │       ├── apple-touch-icon-114x114.png
│   │       ├── apple-touch-icon-120x120.png
│   │       ├── apple-touch-icon-144x144.png
│   │       ├── apple-touch-icon-152x152.png
│   │       ├── apple-touch-icon-172x172.png
│   │       ├── apple-touch-icon-180x180.png
│   │       ├── apple-touch-icon-196x196.png
│   │       ├── apple-touch-icon-29x29.png
│   │       ├── apple-touch-icon-40x40.png
│   │       ├── apple-touch-icon-48x48.png
│   │       ├── apple-touch-icon-55x55.png
│   │       ├── apple-touch-icon-57x57.png
│   │       ├── apple-touch-icon-58x58.png
│   │       ├── apple-touch-icon-60x60.png
│   │       ├── apple-touch-icon-72x72.png
│   │       ├── apple-touch-icon-76x76.png
│   │       ├── apple-touch-icon-80x80.png
│   │       ├── apple-touch-icon-87x87.png
│   │       ├── apple-touch-icon-88x88.png
│   │       ├── apple-touch-icon.png
│   │       ├── apple-touch-icon-precomposed.png
│   │       ├── browserconfig.xml
│   │       ├── favicon-128x128.png
│   │       ├── favicon-16x16.png
│   │       ├── favicon-256x256.png
│   │       ├── favicon-32x32.png
│   │       ├── favicon-48x48.png
│   │       ├── favicon-64x64.png
│   │       ├── favicon-96x96.png
│   │       ├── favicon.ico
│   │       ├── icon-2.svg
│   │       ├── icon-loader.svg
│   │       ├── icon.svg
│   │       ├── loading.gif
│   │       ├── logo-dark.svg
│   │       ├── logo.svg
│   │       ├── manifest.json
│   │       ├── mstile-144x144.png
│   │       ├── mstile-150x150.png
│   │       ├── mstile-310x150.png
│   │       ├── mstile-310x310.png
│   │       ├── mstile-70x70.png
│   │       ├── name-dark.svg
│   │       └── rocketcat.png
│   ├── img
│   │   ├── icons.png
│   │   ├── icons.svg
│   │   └── loader.gif
│   ├── manifest.webapp
│   ├── recorderWorker.js
│   └── sounds
│       ├── door_chime.mp3
│       ├── notify.mp3
│       └── notify.ogg
├── f7146bdb10266bbdf98b62cd3a773b8468b4a1b9.css
├── head.html
└── program.json

7 directories, 81 files

Regards
MaX

**Comment by geekgonecrazy** [comment]
@maxlinux2000 are you using one of our officially recommended deployment methods?  We did recently change things up a little to make a cleaner deploy.

Check: https://github.com/RocketChat/Rocket.Chat/wiki

**Comment by jalagrange** [comment]
I had a similar issue @maxlinux2000 . They way I solved it was by running my server on port 80 with root privileges like it says in the documentation:

sudo su
export ROOT_URL=http://your-host-name.com-as-accessed-from-internet/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=80
