### ISSUE TITLE
Not Connecting to Server

### ISSUE THREAD

**Issue by CrazyCodz** [RocketChat/Rocket.Chat.Cordova#58]
After building the app using this code and running it on device, it takes me the page where I need to enter the server url. I enter the server url but its not going further.
I guess it is not connecting it to the server. There is no action after clicking the connect button. 
I tried multiple server urls (even official rocket chat: https://demo.rocket.chat) but the issue remains.

![rocket](https://cloud.githubusercontent.com/assets/13995678/12387217/ea71ef6e-bdf0-11e5-98fb-05571a2733e9.jpg)

**Comment by tholu** [comment]
I have a similar issue where it is loading forever after entering my server URL (worked before!) on iOS 9.3.

**Comment by rodrigok** [comment]
@CrazyCodz can you use remote inspector (chrome or GapDebugger) to see if you have some erros?

**Comment by geekgonecrazy** [comment]
If still having this issue please reach out in the #support channel on our demo server.
