### ISSUE TITLE
android app don't has notifications

### ISSUE THREAD

**Issue by uwittygit** [RocketChat/Rocket.Chat.Cordova#63]
HI, 
I followed the official document to build the android APP, but there is no notifications when received a new message ,any hints?

**Comment by uwittygit** [comment]
the official app from google play has notifications . but my app didn't. why was that? is there any dfferent configuration?

**Comment by graywolf336** [comment]
The official app uses a push notification gateway which requires the official application to be installed. If you want push notifications, then you're going to have to set that up yourself.

**Comment by valessiobrito** [comment]
@graywolf336 Where is it? How to do?
