### ISSUE TITLE
Can't access to login form on iOS

### ISSUE THREAD

**Issue by Johann-Snapp** [RocketChat/Rocket.Chat.Cordova#65]
I've got an issue accessing to login form on iOS.
Here's what happens:
1. The app starts
2. I put the URL of my rocket.chat server
3. I'm redirected on the sign up form
4. When clicking on the "Back to login form" link, I'm not redirected and stay on the same page

Plus on the signup form, the CSS seems not to be loaded.
Did I miss something ?

![app-server-screen](https://cloud.githubusercontent.com/assets/16921761/12641758/b455bd34-c5b1-11e5-8201-f11aea521f90.png)
![app-server-screen-2](https://cloud.githubusercontent.com/assets/16921761/12641759/b477f638-c5b1-11e5-8d61-c33ddb465fd9.png)
![app-signup-screen](https://cloud.githubusercontent.com/assets/16921761/12641760/b49ddd30-c5b1-11e5-8b88-f19459522f6c.png)

**Comment by geekgonecrazy** [comment]
if you goto:

http://{yourserver}/api/info what version are you running?

Also how did you deploy the server?

**Comment by Johann-Snapp** [comment]
Hello, thx for answer.
I'm using the last version of the server: "0.15.0" installed without docker and running with passenger.

Note: When I'm trying to connect to demo.rocket.chat server, everything works fine.
Plus, is there a way to run properly the application in a browser so that we can fully use the dev tools ?

Edit: I've made a `cordova add platform browser`, `cordova build browser`, `cordova run browser` and it's not working because of a FileTransfertError on the `theme.css` file. Failing with:

```
{
    body: null
    code: 1
    exception: null
    http_status: null
    source: "https://demo.rocket.chat/__cordova/theme.css?6107008"
    target: "filesystem:file:///persistent/httpsdemorocketchat//theme.css"
}
```

**Comment by Johann-Snapp** [comment]
Just fixed it.
It wasn't working because of the previous update from 0.14 to 0.15 which didn't pass well.
Removing the server and directly installing the 0.15 version fixed it.

**Comment by jalagrange** [comment]
Hi @Johann-Snapp, could you please explain a bit better what you mean with "removing the server and directly installing 0.15" means? I am 99% sure I have exactly the same problem. I was running 0.14 and did an update to 0.15 but it is still broken so i don't know what you mean by "directly installing 0.15"

**Comment by Johann-Snapp** [comment]
Hi @jalagrange.
I've just rm -rf the project from my server, removed the mongo database and re-install all from the release.

**Comment by jalagrange** [comment]
hi @Johann-Snapp I finally got the time to do this and I went ahead and updated to 0.16 as well. Now the theme css downloads perfectly but when trying to log in I am getting "failed to connect to server abort abort".

Upon further inspection I see that upon requesting access to http://serverurl/api/info, the console logs the following error:

Failed to register the server http://serverurl

Similar to the issue presented by this thread: #https://github.com/RocketChat/Rocket.Chat/issues/26013
![screen shot 2016-02-06 at 11 38 40 am](https://cloud.githubusercontent.com/assets/59909/12868944/039994da-ccc7-11e5-8151-d043d798d83d.png)

**Comment by jalagrange** [comment]
Alright, final update, it works... But I didn't actually do anything to fix it so I thing the last issues had something to do with the DNS since I had just recently changed them. What is weird is that it allowed access through web and not mobile so I honestly don't know what fixed it. I just simply tried the app a couple of hours later and everything was working. Thanks for all the help

**Comment by grassbl8d** [comment]
Hi, I'm also encountering issue. Can't login to the mobile app. It says Waiting fo Server Connection . Trying again in X Seconds Continuously. I don't have any issues on the mobile web and desktop web versions even if fronting with an Apache Proxy.

**Comment by mknet** [comment]
I got the same issue as @grassbl8d. I'm running 0.21.0. Any hints?

Thank you

Update: I got the same issue on Android.

**Comment by grassbl8d** [comment]
I think you need to pass a parameter when starting it. The mobile host I
just forgot the exact command . The mobile host needs to be passed I i
remember correctly. I was already ble to make it work.

**Comment by mknet** [comment]
Do you mean the ROOT_URL?
