### ISSUE TITLE
about push notifications

### ISSUE THREAD

**Issue by uwittygit** [RocketChat/Rocket.Chat.Cordova#66]
HI, 
I am new to Rocket.Chat.Cordova, I can build the app, set up rocketchat server, I dont have any experience on developing apps,  do you have any detailed document on how to make notification work?
just supposed I can setup or buy one notification server,  (GCM/APN) token is ready.

how should I configure server side or client side?

**Comment by geekgonecrazy** [comment]
Please reach out on our demo for this support request.
