### ISSUE TITLE
Question: Is this not the same with the web version?

### ISSUE THREAD

**Issue by alur222** [RocketChat/Rocket.Chat.Cordova#68]
Hello.

I am learning how to create mobile apps using meteor and cordova. I am confused because I was able to generate a cordova app using the webversion using meteor commands. Are the files here based from the web version (or copied from it) ?

**Comment by Burstaholic** [comment]
Yes, the Android app actually downloads the web app from the server URL you give it and runs it locally, so even if, for example, you switch between two servers running different versions of the web app, your local app will reflect any differences when you switch.

**Comment by bkkilaru** [comment]
@Burstaholic How does it load only 13 files though rather than the 86 during an update?

**Comment by alur222** [comment]
It loads the Web App Version to a "webview". So basically this app is the mobile icon (the one you see in the mobile), the splash screen, the loading screen and the scripts for downloading the webversion. @bkkilaru

**Comment by Sing-Li** [comment]
Closing this since the question has been answered.
