### ISSUE TITLE
missing build instructions?

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat.Cordova#69]
I feel a bit daft but I can't seem to get this to build following the instructions in the readme

`mrplow@mrplow-desktop:~/StudioProjects/Rocket.Chat.Cordova$ cordova prepare -d
Executing "before_prepare"  hook for all plugins.
Resolving module name for q => q
Error: Cannot find module 'ticons'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/home/mrplow/StudioProjects/Rocket.Chat.Cordova/hooks/beforePrepare.js:8:15)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:167:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:145:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
mrplow@mrplow-desktop:~/StudioProjects/Rocket.Chat.Cordova$`

even after installing ticons globally like below I still recieve the same error
sudo npm install -g ticons

**Comment by valessiobrito** [comment]
Compile without complications. alerts and errors that were appearing were for lack of dependence.

```
$ git clone repo
$ cd repo
$ npm install ticons
$ npm install underscore
$ npm install coffee
# need create www/shared/js/android_sender_id.js
# need create www/js/bugsnag_apikey.js
$ cordova platform add android
$ cordova build android
```

**Comment by valessiobrito** [comment]
I update the build instructions:
https://github.com/RocketChat/Rocket.Chat/wiki/Build-the-Android-Cordova-Web-App-and-connect-to-your-own-Rocket.Chat-Server

**Comment by mrplow** [comment]
There we go, that's much better.

Thank you very much @valessiobrito

**Comment by mrplow** [comment]
can you also update the main README.md?
Also the wiki instructions state to install ticons, underscore, and coffee globally, that doesn't seem to work. The instructions on this ticket, installing them locally, do work

**Comment by geekgonecrazy** [comment]
@valessiobrito / @mrplow created a PR with the instructions you guys listed here.  Can you guys give it a once over and see if everything looks right?

**Comment by mrplow** [comment]
@geekgonecrazy 

A bit off, here are my steps that work. I don't know why but it doesn't build for me if I install ticons and underscore globally.

~$ rm -rf Rocket.Chat.Cordova/
~$ git clone https://github.com/RocketChat/Rocket.Chat.Cordova.git
~$ cd Rocket.Chat.Cordova/
~/Rocket.Chat.Cordova$ npm install ticons underscore
~/Rocket.Chat.Cordova$ echo 'Bugsnag.apiKey = "YOUR-API-KEY-HERE";' > www/js/bugsnag_apikey.js
~/Rocket.Chat.Cordova$ echo 'window.ANDROID_SENDER_ID = "YOUR-ANDROID-ID-HERE";' > www/shared/js/android_sender_id.js
~/Rocket.Chat.Cordova$ cordova build android

**Comment by amenk** [comment]
Android ID can be found like this: http://android.stackexchange.com/a/35660/24479
