### ISSUE TITLE
cordova app cannot connect to edited server

### ISSUE THREAD

**Issue by imane12** [RocketChat/Rocket.Chat.Cordova#72]
I edit server Rocket Chat and I run meteor, then I try to connect my android application (Rocket.Chat.Cordova) to our server . it downloads all files but can't connect to server (it show waiting for server connection, trying again ...)

**Comment by tholu** [comment]
I have the same issue with the iOS application from the AppStore.

**Comment by rodrigok** [comment]
@imane12 can you test this? https://github.com/RocketChat/Rocket.Chat.Cordova#i-cant-connect-to-my-server-instance

Please reopen this issue if the problem persists.
