### ISSUE TITLE
Push Notification configuration

### ISSUE THREAD

**Issue by CrazyCodz** [RocketChat/Rocket.Chat.Cordova#76]
How do we configure the push notification for Android and iOS? 

Do we need to do anything to gateway?

**Comment by CrazyCodz** [comment]
Here is the steps which I have followed for the Push notification.

1) Created a new project 
2) Generated a API key of the type browser
3)  Added the record in Administration --> Push 

GCM API Key  = "API key" 
GCM Project Number  = " project number" 

4) Created a file www/js/android_sender_id.js with following
 window.ANDROID_SENDER_ID =  "Project number" 

5) disabled the gateway 

Am I missing anything?

**Comment by CrazyCodz** [comment]
Deleted all the records in _raix_push_app_tokens.  Then deleted all the records. Then logged out of the app then logged back. It created a new record in the table.

**Comment by geekgonecrazy** [comment]
@CrazyCodz did this work?

**Comment by CrazyCodz** [comment]
We got it working for the Android but iOS is still pending. 

The steps I wrote is pretty much what we followed. Are you facing the same issues?

**Comment by geekgonecrazy** [comment]
@CrazyCodz I am not. Just wanted to check in and see if you had figured it out.  Please feel free to reach out to me on the demo server https://demo.rocket.chat
