### ISSUE TITLE
Required Android Version in App Store

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [RocketChat/Rocket.Chat.Cordova#8]
Assuming this repo is what [this app](https://play.google.com/store/apps/details?id=com.konecty.rocket.chat) is built from, is the dependency on android 4.4 absolutely required? I personally use Android 4.2 and one of my team also has an older version (not sure which exactly).

I suggest to keep the value for the required android version as low as possible.

**Comment by Sing-Li** [comment]
Thanks. Please check the wiki for a version that will work with all versions back to 4.0.x!

**Comment by mathias-baumann-sociomantic** [comment]
Ah okay, that would be https://github.com/RocketChat/Rocket.Chat/wiki/Build-the-Android-Cordova-Web-App-and-connect-to-your-own-Rocket.Chat-Server for anyone else who finds this ticket

**Comment by Sing-Li** [comment]
With Meteor 1.2 (any week now) the problem will go away with Google Play version too.  Thanks.
