### ISSUE TITLE
No push notifications

### ISSUE THREAD

**Issue by homberger** [RocketChat/Rocket.Chat.Cordova#81]
I don't receive any push notifications of Rocket.Chat on my iPhone anymore.
Since I applied the "fix" (https://github.com/RocketChat/Rocket.Chat/issues/2399 : setting a word in the "highlight" field) to not receive a push notification for every message in any channel even from myself, I don't receive _any_ push notifications - even when I am mentioned.
Look at attached screenshot to see my profile preferences. Setting a word in the highlight field changes nothing.

<img width="655" alt="screen shot 2016-03-04 at 21 18 07" src="https://cloud.githubusercontent.com/assets/681335/13539126/c74dddfe-e24e-11e5-9908-8b9a4520737e.png">

On the next screenshot you can see our push notification preferences.

<img width="647" alt="screen shot 2016-03-04 at 21 20 58" src="https://cloud.githubusercontent.com/assets/681335/13539189/167dc6d2-e24f-11e5-91be-2c137f3ceaa0.png">

We are using Rocket.Chat 0.20.0 on server side. On my iPhone is the latest release of the iOS cordova app.

**Comment by homberger** [comment]
I deleted and reinstalled the app on my iPhone. When asked for permission to send push notifications I agreed (like before). Still no push notifications.
How can I debug this?

**Comment by rodrigok** [comment]
Hi @homberger, this problem is not related with the mobile app it self.

Can you open this issue in this repository https://github.com/RocketChat/Rocket.Chat?

**Comment by homberger** [comment]
This issue was moved to RocketChat/Rocket.Chat#2431
