### ISSUE TITLE
Not able to access my installation via Mobile Apps

### ISSUE THREAD

**Issue by mknet** [RocketChat/Rocket.Chat.Cordova#83]
As I already wrote in the closed issue #65, I am not able to access my server via the Mobile Apps.

I run the app directly out of the cloned git repo for testing reasons. The thing I don't understand is why does it work perfectly in the browser and within the Mac "Web View App" and theres is not even a request coming to the server while I'm trying to to access it via the iOS or Android app?

Is there a specific setting?
Which URL is used to connect to the server?

Thanks for any hint

**Comment by rodrigok** [comment]
Can you try this? https://github.com/RocketChat/Rocket.Chat.Cordova/blob/develop/README.md#i-cant-connect-to-my-server-instance

**Comment by mknet** [comment]
Thanks, @rodrigok 
After setting this switch, **removing** my former configured server and adding it once more it worked.
Have you already thought about putting this hint also into the README.md of the server project? I didn't take a look at the Cordova project since I wasn't building my app manually.

Thanks

**Comment by rodrigok** [comment]
Great.

Not right now, we are trying to fix this problem first.
