### ISSUE TITLE
custom icons / branding

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat.Cordova#84]
Just figured out how to build Cordova app, and would like some help which graphics to update to change branding for Cordova mobile? 

I think it insists on ImageMagick being present so it can generate the various icons and resolutions? What is the base image file that is used?

**Comment by geekgonecrazy** [comment]
Just the files located there in the image folder

https://github.com/RocketChat/Rocket.Chat.Cordova/blob/develop/hooks/beforePrepare.js#L29

A good place to look.
