### ISSUE TITLE
[iOS] App doesn't use landscape mode

### ISSUE THREAD

**Issue by aNullValue** [RocketChat/Rocket.Chat.Cordova#85]
While using the Rocket.Chat app published via the App Store (https://geo.itunes.apple.com/us/app/rocket.chat/id1028869439?mt=8), the app does not honor landscape orientation of the device. This makes the app completely unusable by anyone using an iPad in landscape orientation (which is almost always the case when you have an attached keyboard).

**Comment by rodrigok** [comment]
Will be fixed on the next version, currently in beta
