### ISSUE TITLE
Mobile App Showing Plain Text

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat.Cordova#86]
When we connect to our RC server from the mobile app we are getting plain text only from both iOS and Android.

Our Rocketchat version is 0.23 with the app version 2.2.2.

I'm not sure if this has to do with some nginx configuration. The server we are accessing ends in .com and it is reverse proxying into our backend that ends in .us. Everything works in the browser fine. I noticed someone in #support has had a similar issue but didn't see a solution.

![img_2724](https://cloud.githubusercontent.com/assets/8405384/14050013/e9e96c28-f286-11e5-960b-9dc4d6acae7f.PNG)

**Comment by mspl13** [comment]
The same issue seems to apply for the Android Version (can only confirm for 4.4.4 and above).
You can actually login by using the username and password fields only, but still there seems to be something wrong (see screenshots below, Android 4.4.4).
![screenshot_2016-03-26-14-29-01](https://cloud.githubusercontent.com/assets/8393513/14060615/c237e38c-f36a-11e5-90e0-9aab4e39c60c.png)
![screenshot_2016-03-26-14-29-42](https://cloud.githubusercontent.com/assets/8393513/14060617/c3f08d6e-f36a-11e5-9eea-03ecfd343600.png)

**Comment by richardwlu** [comment]
Fixed in Rocket.Chat 0.24.
