### ISSUE TITLE
Provide release files on GitHub

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat.Cordova#9]
So Android app was released and is available on the Play, but it is not attached here to the releases. It would be great if it would be possible to get the apk file directly.

**Comment by tkizm1** [comment]
agree

**Comment by geekgonecrazy** [comment]
@mitar once we publish from this branch that will be the case.  :)

Currently its being published from the main repo.  That will change once we get things  functioning here.

**Comment by mitar** [comment]
OK, but things are not available here either: https://github.com/RocketChat/Rocket.Chat/releases

**Comment by rodrigok** [comment]
https://github.com/RocketChat/Rocket.Chat.Cordova/releases/tag/2.0.0.beta.4
