### ISSUE TITLE
Can Not edit / delete messages after update to 2.3 

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Cordova#91]
Hey Guys, 

My rocket.chat server version is 0.25.0. After the update of my mobile app on ios i can't edit my own post. There is no option to do this anymore. Before the update there was a little gear icon then I tab on the messages. 

(Screenshot attached)

Greets 
TheReal

![](http://i.imgur.com/GcpDzEe.jpg)

**Comment by geekgonecrazy** [comment]
@TheReal1604 try long pressing on the message.  Also make sure you're on the latest version of the app.  I think a new version was just released a couple of days ago.

**Comment by TheReal1604** [comment]
@geekgonecrazy Thanks for the hint.. this was new to me. Works like a charm!
